- docs/guides/ha-cluster/readme.md
- docs/guides/index.md
- mkdocs.yml
> First iteration of High Availability Cluster user guide

- docs/guides/compute-daemons/readme.md
Describes the new default behavior added to the [clientmount](https://github.com/HewlettPackard/dws/pull/74) and [nnf-dm](https://github.com/NearNodeFlash/nnf-dm/pull/76) daemons with regards to the `--node-name` and `--nnf-node-name` values.
> Document the default '--node-name' and '--nnf-node-name' behavior

- docs/guides/index.md
- docs/guides/rbac-for-users/readme.md
- mkdocs.yml
This commit provides documentation for creating certs, a kubeconfig, and RBAC rules for allowing users viewer access only.
Signed-off-by: Matt Richerson <matthew.richerson@Matts-MacBook-Pro.local>
> Documentation for RBAC viewer roles.

- docs/guides/ha-cluster/fence_nnf.py
- docs/guides/ha-cluster/notes.md
- docs/guides/ha-cluster/readme.md
1. Updates the readme for
- redfish (final and verified)
- nnf (pending)
2. Adds my in-progress fence_nnf.py changes
3. Adds my notes.md file
> Continued changes for NNF fencing

- docs/rfcs/0002/readme.md
- Remove type specification for storages
- Added `optional` flag to storages
- Added `securityContext` to pod spec to inherit workflow user/group ID permissions
- Added symlinks for Indexed-Mount types
> Update Containers RFC

- docs/guides/ha-cluster/readme.md
The HA cluster should be named after the Rabbit node. Include instructions to make this clear.
> Improve instructions for HA cluster naming

- docs/guides/ha-cluster/readme.md
The ServiceAccount which is create is called nnf-fencing-agent not nnf-fence-agent.
> Fix nnf-fencing-agent ServiceAccount name

- docs/guides/compute-daemons/readme.md
The script as specified is missing a dash for the decode option.
> Add missing dash for --decode

- docs/guides/rbac-for-users/readme.md
This relies on the "RBAC for Users" documentation, and it generalizes those steps a bit to make it easier to cut-n-paste them for the flux user case.
> Document RBAC configuration for Flux

- docs/guides/index.md
- docs/guides/user-containers/readme.md
- mkdocs.yml
Document the use of a private repository for a user's containerized application, and the use of ImagePullSecrets to let k8s access that container.
Create a basic NNF User Container doc to create a place to land the above doc.
> Using a private repository for user containers

- docs/guides/user-containers/readme.md
Show the placement of the imagePullSecrets lists for private MPI container images in the NnfContainerProfile resource.
> Using a private repository for user containers - MPI File Utils

- .gitignore
- docs/guides/compute-daemons/readme.md
- docs/guides/ha-cluster/readme.md
- docs/guides/index.md
- docs/guides/rbac-for-users/readme.md
- docs/guides/user-containers/readme.md
- docs/rfcs/0002/readme.md
- mkdocs.yml
- Add "site/" to .gitignore
- Fix nnf-fencing-agent ServiceAccount name
- Add missing dash for --decode
- Document RBAC configuration for Flux (#62)
- Using a private repository for user containers (#69)
- Containers RFC Update
- Renamed environment variables + remove line breaks
- Updated DNS hostnames/subdomains details + env vars
- Updated containers RFC to account for MPI jobs via mpi-operator
- Remove 'Say'
- Using a private repository for user containers - MPI File Utils (#72)
> Release v0.0.2

- docs/guides/initial-setup/readme.md
Update the cert-manager version.
Remove the cray.nnf.x-name node label, which we've never used.
Refer to the `nnf-deploy init` command for taints and labels, rather then the obsolete init.sh script.
> Updates for NNF dependencies

- docs/guides/compute-daemons/readme.md
The "operator" word was removed in DWS v0.0.13 as part of the move from HewlettPackard/dws to DataWorkflowServices/dws.
> Remove "operator" from service account names and namespaces

- .github/workflows/publish-main.yaml
- .github/workflows/release.yaml
- .gitmodules
- docs/guides/data-movement/copy-offload-api.html
- docs/guides/data-movement/readme.md
- docs/guides/index.md
- mkdocs.yml
The Copy Offload API documentation is auto-generated using a gRPC plugin that produces HTML output. This document resides in the `nnf-dm` repository.
This adds a submodule for `nnf-dm` and a symbolic link to the auto-generated html. This allows the HTML to be displayed directly in the documentation on GitHub pages. Links to the HTML have been added.
The symbolic link should provide seamless support for versioning.
> Added nnf-dm submodule to pull in auto-generated Copy Offload API

- docs/repo-guides/release-nnf-sw/readme.md
It is no longer necessary to manually create releases in the Github GUI or via `gh release create`.
> Describe how a repo is released when a tag is pushed.

- .github/workflows/publish-main.yaml
- docs/repo-guides/release-nnf-sw/readme.md
Documenation should auto-release too.
> Auto-release when a tag is pushed

- docs/guides/index.md
- docs/guides/node-management/drain.md
- mkdocs.yml
NNF Daemonsets will be drained from nodes via the cray.nnf.node.drain taint. The CSI driver must tolerate that so it can stick around and complete the unmounts that k8s will request.
If CSI were allowed to be drained then nothing would remain to satisfy the k8s unmounts, and k8s would leave the NNF software in Terminating state.
> Draining A Node

- docs/guides/global-lustre/readme.md
We should be using the v1beta1 CRD version now.
> Update CRD version on Global Lustre resource

- docs/guides/rbac-for-users/readme.md
Problem: there is a typo in the example ClusterRoleBinding given in the RBAC guide, so it cannot be used as provided.
Fix the typo.
> rbac: fix typo in guide

- docs/guides/initial-setup/readme.md
Node taints and labels are handled by the SystemConfiguration controller, rather than `nnf-deploy init`.
Cert-manager is owned by the manifests which are deployed via ArgoCD, and it no longer needs to be described as a manual step.
> Update description of node taints and labels.

- docs/guides/directive-breakdown/readme.md
- docs/guides/index.md
- mkdocs.yml
Document the DirectiveBreakdown resource and how the WLM should interpret its fields.
> Add documentation for DirectiveBreakdown

- docs/guides/storage-profiles/readme.md
This commit adds documentation for the Lustre layout fields in the NnfStorageProfile.
> Add Lustre Layout documentation to Storage Profile

- docs/guides/index.md
- docs/guides/node-management/nvme-namespaces.md
- mkdocs.yml
Describe how to view total NVMe space available, used, or leaked. Describe how to reclaim leaked NVMe space.
> NVMe namespace management

- docs/guides/rbac-for-users/readme.md
When access to NNF resources is desired, then the WLM would use this ClusterRole rather than the one provided by DWS.
> Add a WLM ClusterRole that can also access some NNF resources

- docs/guides/external-mgs/readme.md
Document how to create the NnfLustreMGT and ConfigMap for MGTs outside of NNF's control.
> Add NnfLustreMGT documentation

- docs/guides/external-mgs/readme.md
- docs/guides/index.md
- docs/guides/node-management/drain.md
- docs/guides/user-interactions/readme.md
- mkdocs.yml
> Release v0.1.6

- docs/guides/index.md
- docs/guides/system-storage/readme.md
- mkdocs.yml
Add docs for how to use the NnfSystemStorage resource to create two VGs to work around the lvmlockd bug.
> System Storage documentation

- docs/guides/initial-setup/readme.md
- docs/guides/system-storage/readme.md
Change the udev options so they work with RAID configurations, and fix the examples in the lvmlockd workaround section for system storage.
> Update udev recommendation and fix system storage examples

- docs/guides/data-movement/copy-offload.md
The github markdown [!NOTE] isn't recognized by mkdocs. Switch to mkdocs admonitions.
https://squidfunk.github.io/mkdocs-material/reference/admonitions/
> Use mkdocs admonitions for notes
